# CMake generated Testfile for 
# Source directory: /home/nerilusherby/raytracer-optimisation-sample/tests
# Build directory: /home/nerilusherby/raytracer-optimisation-sample/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EndToEnd_TwoSpheres "/usr/bin/cmake" "-DRAYTRACER_EXE=/home/nerilusherby/raytracer-optimisation-sample/raytracer" "-DSCENE_FILE=/home/nerilusherby/raytracer-optimisation-sample/scenes/two-spheres-on-plane.json" "-DOUTPUT_FILE=EndToEnd_TwoSpheres.png" "-DREF_FILE=/home/nerilusherby/raytracer-optimisation-sample/readme/two-spheres-on-plane.png" "-DCOMPARATOR_EXE=/home/nerilusherby/raytracer-optimisation-sample/tests/compare_images" "-DTEST_NAME=EndToEnd_TwoSpheres" "-DMETRICS_FILE=/home/nerilusherby/raytracer-optimisation-sample/metrics.csv" "-P" "/home/nerilusherby/raytracer-optimisation-sample/tests/run_test.cmake")
set_tests_properties(EndToEnd_TwoSpheres PROPERTIES  _BACKTRACE_TRIPLES "/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;55;add_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;69;add_raytracer_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;0;")
add_test(EndToEnd_Monkey "/usr/bin/cmake" "-DRAYTRACER_EXE=/home/nerilusherby/raytracer-optimisation-sample/raytracer" "-DSCENE_FILE=/home/nerilusherby/raytracer-optimisation-sample/scenes/monkey-on-plane.json" "-DOUTPUT_FILE=EndToEnd_Monkey.png" "-DREF_FILE=/home/nerilusherby/raytracer-optimisation-sample/readme/monkey-on-plane.png" "-DCOMPARATOR_EXE=/home/nerilusherby/raytracer-optimisation-sample/tests/compare_images" "-DTEST_NAME=EndToEnd_Monkey" "-DMETRICS_FILE=/home/nerilusherby/raytracer-optimisation-sample/metrics.csv" "-P" "/home/nerilusherby/raytracer-optimisation-sample/tests/run_test.cmake")
set_tests_properties(EndToEnd_Monkey PROPERTIES  _BACKTRACE_TRIPLES "/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;55;add_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;74;add_raytracer_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;0;")
add_test(EndToEnd_TwoTriangles "/usr/bin/cmake" "-DRAYTRACER_EXE=/home/nerilusherby/raytracer-optimisation-sample/raytracer" "-DSCENE_FILE=/home/nerilusherby/raytracer-optimisation-sample/scenes/two-triangles-on-plane.json" "-DOUTPUT_FILE=EndToEnd_TwoTriangles.png" "-DREF_FILE=/home/nerilusherby/raytracer-optimisation-sample/readme/two-triangles-on-plane.png" "-DCOMPARATOR_EXE=/home/nerilusherby/raytracer-optimisation-sample/tests/compare_images" "-DTEST_NAME=EndToEnd_TwoTriangles" "-DMETRICS_FILE=/home/nerilusherby/raytracer-optimisation-sample/metrics.csv" "-P" "/home/nerilusherby/raytracer-optimisation-sample/tests/run_test.cmake")
set_tests_properties(EndToEnd_TwoTriangles PROPERTIES  _BACKTRACE_TRIPLES "/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;55;add_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;79;add_raytracer_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;0;")
add_test(EdgeCase_Empty "/usr/bin/cmake" "-DRAYTRACER_EXE=/home/nerilusherby/raytracer-optimisation-sample/raytracer" "-DSCENE_FILE=/home/nerilusherby/raytracer-optimisation-sample/scenes/edge-case-empty.json" "-DOUTPUT_FILE=EdgeCase_Empty.png" "-DREF_FILE=" "-DCOMPARATOR_EXE=/home/nerilusherby/raytracer-optimisation-sample/tests/compare_images" "-DTEST_NAME=EdgeCase_Empty" "-DMETRICS_FILE=/home/nerilusherby/raytracer-optimisation-sample/metrics.csv" "-P" "/home/nerilusherby/raytracer-optimisation-sample/tests/run_test.cmake")
set_tests_properties(EdgeCase_Empty PROPERTIES  _BACKTRACE_TRIPLES "/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;55;add_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;85;add_raytracer_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;0;")
add_test(EndToEnd_FailureDemo "/usr/bin/cmake" "-DRAYTRACER_EXE=/home/nerilusherby/raytracer-optimisation-sample/raytracer" "-DSCENE_FILE=/home/nerilusherby/raytracer-optimisation-sample/scenes/two-spheres-on-plane.json" "-DOUTPUT_FILE=EndToEnd_FailureDemo.png" "-DREF_FILE=/home/nerilusherby/raytracer-optimisation-sample/readme/monkey-on-plane.png" "-DCOMPARATOR_EXE=/home/nerilusherby/raytracer-optimisation-sample/tests/compare_images" "-DTEST_NAME=EndToEnd_FailureDemo" "-DMETRICS_FILE=/home/nerilusherby/raytracer-optimisation-sample/metrics.csv" "-P" "/home/nerilusherby/raytracer-optimisation-sample/tests/run_test.cmake")
set_tests_properties(EndToEnd_FailureDemo PROPERTIES  _BACKTRACE_TRIPLES "/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;55;add_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;95;add_raytracer_test;/home/nerilusherby/raytracer-optimisation-sample/tests/CMakeLists.txt;0;")
